import phpmod;
import std.random;
import std.math;
import core.bitop;

mixin mod!bloom;
@nogc nothrow:


@phpClass struct Bloom {
  BloomFilter!(long, _emalloc, _efree) bf;
  ZendObject obj;

  @hidden:

  this(long expectedItems, double falsePositiveRate = 0.01) {
    if (expectedItems <= 0) {
      throw new Exception("expectedItems has to be positive");
    }
    if (falsePositiveRate < 0.000001 || falsePositiveRate >= 1) {
      throw new Exception("falsePositiveRate has to be between 0 and 1");
    }
    bf = BloomFilter!(long, _emalloc, _efree).create(expectedItems, falsePositiveRate);
  }

  // We need to declare destructor explicitly.
  // Autogenerated one is invisible for phpmod and doesn't get exposed to PHP.
  ~this() {
    destroy(bf);
  }

  pragma(inline, true)
  void add(TypedZval!(long, ZendString*) key) nothrow {
    bf.add(getRealKey(key));
  }

  bool contains(TypedZval!(long, ZendString*) key) nothrow {
    return bf.contains(getRealKey(key));
  }

  pragma(inline, true)
  private long getRealKey(TypedZval!(long, ZendString*) key) nothrow {
    if (auto longPtr = key.asLong) {
      return *longPtr;
    } else {
      auto strPtr = key.asString;
      return strPtr.toHash();
    }
  }
}



private struct BloomFilter(T, alias malloc, alias free) {

  private ulong bitLength;
  private ulong[] arr; 
  private size_t nHashFunctions;

  nothrow @hidden:

  static create(size_t expectedItems, double falsePositiveRate) {
    auto bits   = ceil(-(expectedItems * log(falsePositiveRate)) / log(pow(2.0, log(2.0))));
    auto hashes = round(log(2.0) * bits / expectedItems);
    return BloomFilter!(T, malloc, free)(cast(long) hashes, cast(long) bits);
  }

  this(size_t nHashFunctions, size_t bitLength) in (nHashFunctions > 0 && bitLength >= 64) {
    this.bitLength = higherPowerOfTwo(bitLength);
    this.arr = (cast(ulong*) malloc(this.bitLength / 8))[0 .. this.bitLength / 64];
    this.arr[] = 0;
    this.nHashFunctions = nHashFunctions;
  }

  ~this() {
    free(arr.ptr);
  }

  private static ulong higherPowerOfTwo(size_t x) =>
    x == 1 ? 1UL : 1UL << (bsr(x - 1) + 1);

  pragma(inline, true)
  private auto hash(size_t i, T x) =>
    hashFunctions[i].hash(x) & (bitLength - 1);

  pragma(inline, true)
  private void setBit(size_t pos) {
    arr.ptr[pos / 64] |= (1UL << (pos % 64));
  }
  pragma(inline, true)
  private bool getBit(size_t pos) {
    return (arr.ptr[pos / 64] & (1UL << (pos % 64))) != 0;
  }

  void add(T x) {
    foreach (i; 0 .. nHashFunctions) {
      setBit(hash(i, x));
    }
  }

  bool contains(T x) {
    foreach (i; 0 .. nHashFunctions) {
      if (!getBit(hash(i, x))) {
        return false;
      }
    }
    return true;
  }
}



struct HashFunc {
  ulong M, a, b;
  pragma(inline, true)
  ulong hash(ulong x) const nothrow @nogc => (a * x + b) >> (64 - M);
}

private auto makeHashFunc(uint seed, int randomBits = 32) {
  auto rand = Xorshift(seed);
  ulong getRandLong() {
    ulong a = rand.front; rand.popFront();
    ulong b = rand.front; rand.popFront();
    return a ^ (b << 32);
  }
  return HashFunc(
    M: randomBits,
    a: getRandLong() | 1UL,                            // random odd positive integer (a < 2^w)
    b: getRandLong() & ((1UL << (64-randomBits)) - 1), // random non-negative integer (b < 2^(w-M))
  );
}

immutable HashFunc[64] hashFunctions = (() {
  HashFunc[64] hs;
  foreach (i, ref h; hs) {
    h = makeHashFunc(cast(uint)(i * 1337 * 1337 * 1337));
  }
  return hs;
})();
